name: Terraform FMT and Validate

on:
  pull_request:
    branches:
      - main   

jobs:
  terraform:
    name: Terraform Format and Validate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.0

    - name: Initialize Terraform
      run: terraform init

    - name: Run Terraform FMT recursively
      run: terraform fmt -recursive -check    

    - name: Validate Terraform
      run: terraform validate
